# Generated by Django 2.2.3 on 2019-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_view',
            field=models.ImageField(upload_to=''),
        ),
    ]
